repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        files: ".ipynb"
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ['--ignore=E203, E266, E401, E501, W503, F403, F401', '--max-line-length=120']
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --disallow-untyped-defs]
        files: notebooks/
      - id: mypy
        args: [--ignore-missing-imports, --disallow-untyped-defs]
        files: src/
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [ "--multi-line=5", "--line-length=120", "--use-parentheses", "--filter-files" ]
        exclude: "migrations"
