# Data path config
external_data_path: data_blobs/external/
interim_data_path: data_blobs/interim/
processed_data_path: data_blobs/processed/
raw_data_path: data_blobs/raw/

# Logger config
log_dir_name: logs

# Model config
model_weights_dir: model_weights/
model_log_dir: model_logs/
