external_data_path: data_blobs/external/
interim_data_path: data_blobs/interim/
processed_data_path: data_blobs/processed/
raw_data_path: data_blobs/raw/

model_weights_dir: model_weights/
model_log_dir: model_logs/

# Add model configs here
